name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: src/ReshadeEffectShaderToggler.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

concurrency:
  group: msbuild-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build x64
        run: msbuild /m /property:Platform=x64 /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}

      - name: Build x86
        run: msbuild /m /property:Platform=x86 /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: REST-build-${{ github.sha }}
          path: |
            src/x64/Release/ReshadeEffectShaderToggler.addon64
            src/Win32/Release/ReshadeEffectShaderToggler.addon32
          if-no-files-found: error
          retention-days: 14
